
title: VincentğŸ˜Š
author: Vincent Lau
email: mrliuyiman@foxmail.com
wechat: mrliuyiman
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  vincentmrlau

# é¡µè„šå…¶ä»–ä¸»é¡µ
moreSite: [
 {
  name: 'vincentmrlau',
  href: 'https://github.com/vincentmrlau',
  icon: '../assets/github.png'
 },
 {
   name: 'æ–‡æ£®ç‰¹æ',
   href: 'https://github.com/vincentmrlau',
   icon: '../assets/zhihu.png'
  },
  {
    name: 'vincent4fun',
    href: 'https://segmentfault.com/u/vincent4fun',
    icon: '../assets/segmentfault.png'
   },
   {
    name: 'vincentlau',
    href: 'https://www.npmjs.com/~vincentlau',
    icon: '../assets/npm.png'
   }
]

# è¿™é‡Œæ˜¯èœå•
menu: [
  {
    name: 'Timelineâ³',
    href: '/timeline/'
  },
  {
    name: 'CategoriesğŸ°',
    href: '/categories/'
  },
  {
    name: 'AboutğŸ‘»',
    href: '/about/'
  }
]

# Build settings
markdown: kramdown

plugins:
  - jekyll-feed

